language: cpp
sudo: required
dist: trusty

env:
    global:
        - CC=gcc-4.9
        - CXX=g++-4.9
    matrix:
        - BUILD_TYPE=Release
        - BUILD_TYPE=Debug

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9-multilib

before_install:
  - sudo update-alternatives  --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 99 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo update-alternatives --auto gcc
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libssl-dev:i386
  - sudo apt-get -yq --force-yes remove libssl-dev libssl
  
  - wget "https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh"
  - sudo sh cmake-3.6.3-Linux-x86_64.sh --exclude-subdir --prefix=/usr
  
  - wget "http://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz"
  - tar xzf boost_1_62_0.tar.gz

install:
  - cd boost_1_62_0/
  - if [ ! -f "b2" ]; then sudo bash bootstrap.sh --prefix=/usr/local --with-libraries=system; fi
  - sudo ./b2 variant=${BUILD_TYPE,,} link=static threading=multi address-model=32 runtime-link=shared -j2 -d0 install
  - cd ..
  - sudo ldconfig

before_script:
  - cmake . -D_OPENSSL_LIBDIR="/usr/lib/i386-linux-gnu" -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - make -j2
  - make package

