version: '{build}'
image: Visual Studio 2017

configuration:
    # OpenSSL static libs are not compiled with msvc14
    # links to dynamic OpenSSL libs
    - Debug
    - Release

platform: x86

clone_depth: 1

environment:
    BOOST_ROOT: C:/Libraries/boost_1_64_0
    BOOST_LIBRARYDIR: C:/Libraries/boost_1_64_0/lib32-msvc-14.1

install:
    - git submodule update --init --recursive

before_build:
    - cmake . -G "Visual Studio 15 2017" -DOPENSSL_USE_STATIC_LIBS=OFF -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
build_script:
    - cmake --build . --config %CONFIGURATION%
    - cmake --build . --config %CONFIGURATION% --target package

artifacts:
    - path: discord-connector-*-win32.zip
      name: DCC plugin

