name: Build

on:
  push:
    branches:
      - 'master' 
      - 'github-actions' # temp
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04]
        build-type: [Debug]
        include:
          - os: windows-latest
            cmake-args: '-AWin32 -Thost=x86'
          - os: ubuntu-18.04
            cmake-args: '-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32'

    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set env
      run: echo "REPO_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
      shell: bash
    
    - name: get-cmake
      uses: lukka/get-cmake@v3.19.0

    - if: runner.os == 'Linux'
      name: Install gcc/g++-multilib for linux
      run: |
        sudo apt-get update
        sudo apt install gcc-multilib g++-multilib
        sudo apt install libboost-all-dev

    - if: runner.os == 'Windows'
      name: Set boost_root to BOOST_ROOT_1_72_0
      run: echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
      shell: bash
      
    - name: Get python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0 # SemVer's version range syntax

    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan remote add conan-transit-legacy https://api.bintray.com/conan/conan/conan-transit

    - name: Configure cmake & build
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ runner.workspace }}/build'
        cmakeAppendedArgs: '${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DDCC_VERSION=${{ env.REPO_TAG }} -DGH_ACBUILD=TRUE -DBOOST_ROOT=${{ env.BOOST_ROOT }}'

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: discord-connector-${{ env.REPO_TAG }}-${{ runner.os }}-${{ matrix.build-type }}
        path: ${{ runner.workspace }}/build/artifact/