name: Release build

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04]
        build-type: [Debug, Release]
        include:
          - os: windows-latest
            cmake-args: '-AWin32 -Thost=x86'
          - os: ubuntu-18.04
            cmake-args: '-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32'

    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set release env
      run: echo "REPO_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      shell: bash

    - run: echo "tag = ${{env.REPO_TAG}}"
    
    - name: get-cmake
      uses: lukka/get-cmake@v3.19.0

    - if: runner.os == 'Linux'
      name: Install gcc/g++-multilib for linux
      run: sudo apt install gcc-multilib g++-multilib

    - name: Get python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0 # SemVer's version range syntax

    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan remote add conan-transit-legacy https://api.bintray.com/conan/conan/conan-transit

    - name: Configure cmake & build
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ runner.workspace }}/build'
        cmakeAppendedArgs: '${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DDCC_VERSION=${{ env.REPO_TAG }} -DGH_ACBUILD=TRUE'

    - if: ${{ matrix.build-type }} == 'Release'
      name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: discord-connector-${{ env.REPO_TAG }}-${{ runner.os }}
        path: ${{ runner.workspace }}/build/artifact/
        
    - if: ${{ matrix.build-type }} == 'Debug'
      name: Upload debug artifact
      uses: actions/upload-artifact@v2
      with:
        name: discord-connector-${{ env.REPO_TAG }}-${{ runner.os }}-${{ matrix.build-type }}
        path: ${{ runner.workspace }}/build/artifact/